# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef472693d2c706e134709a370cf35a51e7a0c9eacf01f31d8beafc287237f7accd4052e22451d92652cd22fe6f10a75d64e9a95194b3ff4adeed75d851e27d3

test:
  secret_key_base: 9e07ce5e620fc96da5aed58fc5ad35ca4f22323c47d360b4939319e07662919a02c7bed82458ae707fceb04021d4743335bb3380d877f210844c2e76affaee6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
